---
title: Proyecto Análisis Exploratorio de Datos
author:
  - name: María de los Ángeles Díaz Castro
  - name: Irene Barba La Orden
  - name: Ana Blasco Vega
# affiliation:
#   - num: 1
#     email: diazcas2@alumni.uv.es
#   - num: 2
#     email: ibarlaor@alumni.uv.es
#   - num: 3
#     email: ablasve@alumni.uv.es

#authorcitation: |
 # Leutnant, D.; Doe, J.
# firstnote to eighthnote
#firstnote: |
  #Current address: Updated affiliation
#secondnote: |
# These authors contributed equally to this work.
#correspondence: |
 # leutnant@fh-muenster.de; Tel.: +XX-000-00-0000.
# document options
journal: notspecified
type: article
status: submit
# front matter
simplesummary: |
  Preparación y análisis exploratorio del tráfico diario de carreteras en Valencia 2025, obtenido de la página oficial de la Generalitat Valenciana.
abstract: |
  Este proyecto tiene como objetivo analizar el tráfico en Valencia durante 2025, utilizando datos del dataset público proporcionado por la Generalitat Valenciana. Se consideran 18 variables, de las que se incluyen el número de vehículos que transitan por cada tramo, el método de captación o las coordenadas iniciales y finales de cada registro, entre otras. En total, se han recopilado 15.235 observaciones asociadas a distintos momentos en los que se registró tráfico. Los datos se reestructuraron para facilitar un análisis exploratorio previo, identificando patrones de circulación y posibles anomalías, tratando de ofrecer información valiosa para mejorar la gestión del tráfico y la planificación de las carreteras en Valencia.

keywords: | 

# back matter
acknowledgement: |
  All sources of funding of the study should be disclosed. 
authorcontributions: |
  For research articles with several authors, a short paragraph specifying their 
  individual contributions must be provided.
funding: |
 
institutionalreview: |
  In this section, you should add the Institutional Review Board Statement and 
  approval number, if relevant to your study. You might choose to exclude 
  this statement if the study did not require ethical approval. Please note 
  that the Editorial Office might ask you for further information. Please add 
  “The study was conducted in accordance with the Declaration of Helsinki, 
  and approved by the Institutional Review Board (or Ethics Committee) of 
  NAME OF INSTITUTE (protocol code XXX and date of approval).” for studies 
  involving humans. OR “The animal study protocol was approved by the 
  Institutional Review Board (or Ethics Committee) of NAME OF INSTITUTE 
  (protocol code XXX and date of approval).” for studies involving animals. 
  OR “Ethical review and approval were waived for this study due to REASON 
  (please provide a detailed justification).” OR “Not applicable” for
   studies not involving humans or animals.
informedconsent: |
  Any research article describing a study involving humans should contain this 
  statement. Please add ``Informed consent was obtained from all subjects 
  involved in the study.'' OR ``Patient consent was waived due to REASON 
  (please provide a detailed justification).'' OR ``Not applicable'' for 
  studies not involving humans. You might also choose to exclude this statement 
  if the study did not involve humans.
  
  Written informed consent for publication must be obtained from participating 
  patients who can be identified (including by the patients themselves). Please 
  state ``Written informed consent has been obtained from the patient(s) to 
  publish this paper'' if applicable.
dataavailability: |
  We encourage all authors of articles published in MDPI journals to share 
  their research data. In this section, please provide details regarding where 
  data supporting reported results can be found, including links to publicly 
  archived datasets analyzed or generated during the study. Where no new data 
  were created, or where data is unavailable due to privacy or ethical 
  re-strictions, a statement is still required. Suggested Data Availability 
  Statements are available in section “MDPI Research Data Policies” at 
  \url{https://www.mdpi.com/ethics}.
conflictsofinterest: |
  Declare conflicts of interest or state 'The authors declare no conflict of 
  interest.' Authors must identify and declare any personal circumstances or
  interest that may be perceived as inappropriately influencing the
  representation or interpretation of reported research results. Any role of the
  funding sponsors in the design of the study; in the collection, analyses or 
  interpretation of data in the writing of the manuscript, or in the decision to 
  publish the results must be declared in this section. If there is no role, 
  please state 'The founding sponsors had no role in the design of the study; 
  in the collection, analyses, or interpretation of data; in the writing of the 
  manuscript, an in the decision to publish the results'.
supplementary: |
 The following supporting information can be downloaded at:  
 \linksupplementary{s1}, Figure S1: title; Table S1: title; Video S1: title.
abbreviations:
  - short: MDPI
    long: Multidisciplinary Digital Publishing Institute
  - short: DOAJ
    long: Directory of open access journals
  - short: TLA
    long: Three letter acronym
  - short: LD 
    long: linear dichroism
bibliography: mybibfile.bib
appendix: appendix.tex
endnotes: false
output: 
  rticles::mdpi_article:
    extra_dependencies: longtable
---

\begin{enumerate}
\item *TRAM*: Código del tramo al que se le asocia el tráfico.
\subitem  Primer y segundo dígito: código CV- de la carretera; tres últimos dígitos: número de tramo.
\item *DIA*: Fecha de los datos.
\item *INTA*: Total de vehículos que transitan en el sentido ascendente de la kilometración de la carretera.
\item *INTAP*: Total de vehículos pesados que transitan en el sentido ascendente de la kilometración de la carretera.
\item *INTD*: Total de vehículos que transitan en el sentido descendente de la kilometración de la carretera.
\item *INTDP*: Total de vehículos pesados que transitan en el sentido descendente de la kilometración de la carretera.
\item *INTT*: Total de vehículos que pasan por el tramo analizado (este dato será la suma de los dos sentidos anteriores).
\item *INTTP*: Total de vehículos pesados que pasan por el tramo analizado (este dato será la suma de los dos sentidos anteriores).
\item *TIPUSV*: Tipo de vía (Autovía, Convencional o Desdoblada).
\item *TIPUSE*: Procedimiento de captura de tráfico (Espiras, Gomas Neumáticas, Cámaras o Radar).
\item *PKE*: Posición, en metros, donde se ha captado el tráfico, tomando como referencia la placa de kilometraje anterior en sentido ascendente.
\item *PKECOOR*: Coordenadas geodésicas en latitud y longitud del punto donde se mide el tráfico.
\item *PKINI*: Posición inicial del tramo al que se asocia el tráfico, en metros, tomando como referencia la placa kilométrica anterior en sentido ascendente (tráfico invariante en todo el tramo).
\item *REFINI*: Ubicación del inicio del tramo al que se asocia el tráfico.
\item *PKINICOOR*: Coordenadas geodésicas en latitud y longitud del punto inicial del tramo al que se asocia el tráfico (tráfico invariante en todo el tramo).
\item *PKFI*: Posición final del tramo al que se asocia el tráfico, en metros,tomando como referencia la placa kilométrica anterior en sentido ascendente (tráfico invariante en todo el tramo).
\item *REFFI*: Ubicación del final del tramo al que se asocia el tráfico.
\item *PKFICOOR*: Coordenadas geodésicas en latitud y longitud del punto final del tramo al que se asocia el tráfico (tráfico invariante en todo el tramo).

\end{enumerate}