%  LaTeX support: latex@mdpi.com
%  For support, please attach all files needed for compiling as well as the log file, and specify your operating system, LaTeX version, and LaTeX editor.

%=================================================================
% pandoc conditionals added to preserve backwards compatibility with previous versions of rticles

\documentclass[notspecified,article,submit,moreauthors,pdftex]{Definitions/mdpi}


%% Some pieces required from the pandoc template
\setlist[itemize]{leftmargin=*,labelsep=5.8mm}
\setlist[enumerate]{leftmargin=*,labelsep=4.9mm}


%--------------------
% Class Options:
%--------------------
%----------
% journal
%----------
% Choose between the following MDPI journals:
% acoustics, actuators, addictions, admsci, adolescents, aerobiology, aerospace, agriculture, agriengineering, agrochemicals, agronomy, ai, air, algorithms, allergies, alloys, analytica, analytics, anatomia, animals, antibiotics, antibodies, antioxidants, applbiosci, appliedchem, appliedmath, applmech, applmicrobiol, applnano, applsci, aquacj, architecture, arm, arthropoda, arts, asc, asi, astronomy, atmosphere, atoms, audiolres, automation, axioms, bacteria, batteries, bdcc, behavsci, beverages, biochem, bioengineering, biologics, biology, biomass, biomechanics, biomed, biomedicines, biomedinformatics, biomimetics, biomolecules, biophysica, biosensors, biotech, birds, bloods, blsf, brainsci, breath, buildings, businesses, cancers, carbon, cardiogenetics, catalysts, cells, ceramics, challenges, chemengineering, chemistry, chemosensors, chemproc, children, chips, cimb, civileng, cleantechnol, climate, clinpract, clockssleep, cmd, coasts, coatings, colloids, colorants, commodities, compounds, computation, computers, condensedmatter, conservation, constrmater, cosmetics, covid, crops, cryptography, crystals, csmf, ctn, curroncol, cyber, dairy, data, ddc, dentistry, dermato, dermatopathology, designs, devices, diabetology, diagnostics, dietetics, digital, disabilities, diseases, diversity, dna, drones, dynamics, earth, ebj, ecologies, econometrics, economies, education, ejihpe, electricity, electrochem, electronicmat, electronics, encyclopedia, endocrines, energies, eng, engproc, entomology, entropy, environments, environsciproc, epidemiologia, epigenomes, est, fermentation, fibers, fintech, fire, fishes, fluids, foods, forecasting, forensicsci, forests, foundations, fractalfract, fuels, future, futureinternet, futurepharmacol, futurephys, futuretransp, galaxies, games, gases, gastroent, gastrointestdisord, gels, genealogy, genes, geographies, geohazards, geomatics, geosciences, geotechnics, geriatrics, grasses, gucdd, hazardousmatters, healthcare, hearts, hemato, hematolrep, heritage, higheredu, highthroughput, histories, horticulturae, hospitals, humanities, humans, hydrobiology, hydrogen, hydrology, hygiene, idr, ijerph, ijfs, ijgi, ijms, ijns, ijpb, ijtm, ijtpp, ime, immuno, informatics, information, infrastructures, inorganics, insects, instruments, inventions, iot, j, jal, jcdd, jcm, jcp, jcs, jcto, jdb, jeta, jfb, jfmk, jimaging, jintelligence, jlpea, jmmp, jmp, jmse, jne, jnt, jof, joitmc, jor, journalmedia, jox, jpm, jrfm, jsan, jtaer, jvd, jzbg, kidneydial, kinasesphosphatases, knowledge, land, languages, laws, life, liquids, literature, livers, logics, logistics, lubricants, lymphatics, machines, macromol, magnetism, magnetochemistry, make, marinedrugs, materials, materproc, mathematics, mca, measurements, medicina, medicines, medsci, membranes, merits, metabolites, metals, meteorology, methane, metrology, micro, microarrays, microbiolres, micromachines, microorganisms, microplastics, minerals, mining, modelling, molbank, molecules, mps, msf, mti, muscles, nanoenergyadv, nanomanufacturing,\gdef\@continuouspages{yes}} nanomaterials, ncrna, ndt, network, neuroglia, neurolint, neurosci, nitrogen, notspecified, %%nri, nursrep, nutraceuticals, nutrients, obesities, oceans, ohbm, onco, %oncopathology, optics, oral, organics, organoids, osteology, oxygen, parasites, parasitologia, particles, pathogens, pathophysiology, pediatrrep, pharmaceuticals, pharmaceutics, pharmacoepidemiology,\gdef\@ISSN{2813-0618}\gdef\@continuous pharmacy, philosophies, photochem, photonics, phycology, physchem, physics, physiologia, plants, plasma, platforms, pollutants, polymers, polysaccharides, poultry, powders, preprints, proceedings, processes, prosthesis, proteomes, psf, psych, psychiatryint, psychoactives, publications, quantumrep, quaternary, qubs, radiation, reactions, receptors, recycling, regeneration, religions, remotesensing, reports, reprodmed, resources, rheumato, risks, robotics, ruminants, safety, sci, scipharm, sclerosis, seeds, sensors, separations, sexes, signals, sinusitis, skins, smartcities, sna, societies, socsci, software, soilsystems, solar, solids, spectroscj, sports, standards, stats, std, stresses, surfaces, surgeries, suschem, sustainability, symmetry, synbio, systems, targets, taxonomy, technologies, telecom, test, textiles, thalassrep, thermo, tomography, tourismhosp, toxics, toxins, transplantology, transportation, traumacare, traumas, tropicalmed, universe, urbansci, uro, vaccines, vehicles, venereology, vetsci, vibration, virtualworlds, viruses, vision, waste, water, wem, wevj, wind, women, world, youth, zoonoticdis 
% For posting an early version of this manuscript as a preprint, you may use "preprints" as the journal. Changing "submit" to "accept" before posting will remove line numbers.

%---------
% article
%---------
% The default type of manuscript is "article", but can be replaced by: 
% abstract, addendum, article, book, bookreview, briefreport, casereport, comment, commentary, communication, conferenceproceedings, correction, conferencereport, entry, expressionofconcern, extendedabstract, datadescriptor, editorial, essay, erratum, hypothesis, interestingimage, obituary, opinion, projectreport, reply, retraction, review, perspective, protocol, shortnote, studyprotocol, systematicreview, supfile, technicalnote, viewpoint, guidelines, registeredreport, tutorial
% supfile = supplementary materials

%----------
% submit
%----------
% The class option "submit" will be changed to "accept" by the Editorial Office when the paper is accepted. This will only make changes to the frontpage (e.g., the logo of the journal will get visible), the headings, and the copyright information. Also, line numbering will be removed. Journal info and pagination for accepted papers will also be assigned by the Editorial Office.

%------------------
% moreauthors
%------------------
% If there is only one author the class option oneauthor should be used. Otherwise use the class option moreauthors.

%---------
% pdftex
%---------
% The option pdftex is for use with pdfLaTeX. Remove "pdftex" for (1) compiling with LaTeX & dvi2pdf (if eps figures are used) or for (2) compiling with XeLaTeX.

%=================================================================
% MDPI internal commands - do not modify
\firstpage{1} 
\makeatletter 
\setcounter{page}{\@firstpage} 
\makeatother
\pubvolume{1}
\issuenum{1}
\articlenumber{0}
\pubyear{2024}
\copyrightyear{2024}
%\externaleditor{Academic Editor: Firstname Lastname}
\datereceived{ } 
\daterevised{ } % Comment out if no revised date
\dateaccepted{ } 
\datepublished{ } 
%\datecorrected{} % For corrected papers: "Corrected: XXX" date in the original paper.
%\dateretracted{} % For corrected papers: "Retracted: XXX" date in the original paper.
\hreflink{https://doi.org/} % If needed use \linebreak
%\doinum{}
%\pdfoutput=1 % Uncommented for upload to arXiv.org
%\CorrStatement{yes}  % For updates


%=================================================================
% Add packages and commands here. The following packages are loaded in our class file: fontenc, inputenc, calc, indentfirst, fancyhdr, graphicx, epstopdf, lastpage, ifthen, float, amsmath, amssymb, lineno, setspace, enumitem, mathpazo, booktabs, titlesec, etoolbox, tabto, xcolor, colortbl, soul, multirow, microtype, tikz, totcount, changepage, attrib, upgreek, array, tabularx, pbox, ragged2e, tocloft, marginnote, marginfix, enotez, amsthm, natbib, hyperref, cleveref, scrextend, url, geometry, newfloat, caption, draftwatermark, seqsplit
% cleveref: load \crefname definitions after \begin{document}

%=================================================================
% Please use the following mathematics environments: Theorem, Lemma, Corollary, Proposition, Characterization, Property, Problem, Example, ExamplesandDefinitions, Hypothesis, Remark, Definition, Notation, Assumption
%% For proofs, please use the proof environment (the amsthm package is loaded by the MDPI class).

%=================================================================
% Full title of the paper (Capitalized)
\Title{Proyecto Análisis Exploratorio de Datos}

% MDPI internal command: Title for citation in the left column
\TitleCitation{Proyecto Análisis Exploratorio de Datos}

% Author Orchid ID: enter ID or remove command
%\newcommand{\orcidauthorA}{0000-0000-0000-000X} % Add \orcidA{} behind the author's name
%\newcommand{\orcidauthorB}{0000-0000-0000-000X} % Add \orcidB{} behind the author's name


% Authors, for the paper (add full first names)
\Author{María de los Ángeles Díaz Castro$^{}$, Irene Barba La
Orden$^{}$, Ana Blasco Vega$^{}$}


%\longauthorlist{yes}


% MDPI internal command: Authors, for metadata in PDF
\AuthorNames{María de los Ángeles Díaz Castro, Irene Barba La Orden, Ana
Blasco Vega}

% MDPI internal command: Authors, for citation in the left column

% Affiliations / Addresses (Add [1] after \address if there is only one affiliation.)
\address{%
}

% Contact information of the corresponding author
\corres{Correspondence: }

% Current address and/or shared authorship








% The commands \thirdnote{} till \eighthnote{} are available for further notes

% Simple summary

%\conference{} % An extended version of a conference paper

% Abstract (Do not insert blank lines, i.e. \\)


% Keywords

% The fields PACS, MSC, and JEL may be left empty or commented out if not applicable
%\PACS{J0101}
%\MSC{}
%\JEL{}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Diversity
%\LSID{\url{http://}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Applied Sciences

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Data



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Toxins


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Encyclopedia


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Advances in Respiratory Medicine
%\addhighlights{yes}
%\renewcommand{\addhighlights}{%

%\noindent This is an obligatory section in “Advances in Respiratory Medicine”, whose goal is to increase the discoverability and readability of the article via search engines and other scholars. Highlights should not be a copy of the abstract, but a simple text allowing the reader to quickly and simplified find out what the article is about and what can be cited from it. Each of these parts should be devoted up to 2~bullet points.\vspace{3pt}\\
%\textbf{What are the main findings?}
% \begin{itemize}[labelsep=2.5mm,topsep=-3pt]
% \item First bullet.
% \item Second bullet.
% \end{itemize}\vspace{3pt}
%\textbf{What is the implication of the main finding?}
% \begin{itemize}[labelsep=2.5mm,topsep=-3pt]
% \item First bullet.
% \item Second bullet.
% \end{itemize}
%}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}


% Add imagehandling
% Custom command from Pandoc 3.2.1 to scale images if necessary
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
\makeatother




\begin{document}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Introducción.}\label{introducciuxf3n.}

El tráfico de vehículos va más allá de los números, muestra cómo
Valencia se mueve, organiza y enfrenta cada día sus desafíos de
desplazamiento. Este proyecto se centra en analizar la intensidad del
tráfico en las carreteras de la Comunidad Valenciana durante el primer
semestre de 2025, a partir de datos públicos proporcionados por la
Generalidad Valenciana. A través de un análisis exploratorio de 15.235
observaciones, se busca detectar las posibles anomalías en el tráfico y
explorar el comportamiento de la movilidad en Valencia.

\section{Importación de los datos.}\label{importaciuxf3n-de-los-datos.}

Para importar los datos, primero se descarga el fichero y se verifica
que los datos estén en el directorio adecuado. Es importante especificar
el encoding (en nuestro caso es UTF-8), ya que, de lo contrario, algunos
caracteres pueden no reconocerse correctamente. De esta forma, haciendo
uso de la función de importación en R con los parámetros adecuados,
obtenemos el dataset.

Las variables de nuestro dataset son las siguientes:

\begin{enumerate}
\item \textbf{TRAM} (\textit{numérico}): Código del tramo al que se le asocia el tráfico.
\subitem  Primer y segundo dígito: código CV- de la carretera; tres últimos dígitos: número de tramo.
\item \textbf{DIA} (\textit{carácter}): Fecha de los datos.
\item \textbf{INTA} (\textit{numérico}): Total de vehículos que transitan en el sentido ascendente de la kilometración de la carretera.
\item \textbf{INTAP} (\textit{numérico}): Total de vehículos pesados que transitan en el sentido ascendente de la kilometración de la carretera.
\item \textbf{INTD} (\textit{numérico}): Total de vehículos que transitan en el sentido descendente de la kilometración de la carretera.
\item \textbf{INTDP} (\textit{numérico}): Total de vehículos pesados que transitan en el sentido descendente de la kilometración de la carretera.
\item \textbf{INTT} (\textit{numérico}): Total de vehículos que pasan por el tramo analizado (este dato será la suma de los dos sentidos anteriores).
\item \textbf{INTTP} (\textit{numérico}): Total de vehículos pesados que pasan por el tramo analizado (este dato será la suma de los dos sentidos anteriores).
\item \textbf{TIPUSV} (\textit{carácter}): Tipo de vía (Autovía, Convencional o Desdoblada).
\item \textbf{TIPUSE} (\textit{carácter}): Procedimiento de captura de tráfico (Espiras, Gomas Neumáticas, Cámaras o Radar).
\item \textbf{PKE} (\textit{numérico}): Posición exacta, en metros, donde se ha captado el tráfico, tomando como referencia la placa de kilometraje anterior en sentido ascendente.
\item \textbf{PKECOOR} (\textit{carácter}): Coordenadas geodésicas en latitud y longitud del punto donde se mide el tráfico.
\item \textbf{PKINI} (\textit{numérico}): Posición inicial del tramo al que se asocia el tráfico, en metros, tomando como referencia la placa kilométrica anterior en sentido ascendente (tráfico invariante en todo el tramo).
\item \textbf{REFINI} (\textit{carácter}): Ubicación del inicio del tramo al que se asocia el tráfico.
\item \textbf{PKINICOOR} (\textit{carácter}): Coordenadas geodésicas en latitud y longitud del punto inicial del tramo al que se asocia el tráfico (tráfico invariante en todo el tramo).
\item \textbf{PKFI} (\textit{numérico}): Posición final del tramo al que se asocia el tráfico, en metros,tomando como referencia la placa kilométrica anterior en sentido ascendente (tráfico invariante en todo el tramo).
\item \textbf{REFFI} (\textit{carácter}): Ubicación del final del tramo al que se asocia el tráfico.
\item \textbf{PKFICOOR} (\textit{carácter}): Coordenadas geodésicas en latitud y longitud del punto final del tramo al que se asocia el tráfico (tráfico invariante en todo el tramo).
\end{enumerate}

Si le echamos un vistazo a las variables, podemos ver que la variable
\(DIA\) es de tipo character, por lo que es necesario convertirla a
formato de fecha. Para ello, usamos la función as.Date(). Por otro lado,
es importante preguntarse con cuántos valores faltantes estamos
trabajando, para ello usamos is.na() y sumamos los valores faltantes,
obteniendo:

\begin{verbatim}
## [1] 0
\end{verbatim}

Como no tenemos valores faltantes, no será necesario llevar a cabo
ningún proceso de imputación o similar.

\section{Conversión de los datos a estructura
Tidy.}\label{conversiuxf3n-de-los-datos-a-estructura-tidy.}

La estructura tidy se caracteriza por tener cada variable en una
columna, cada observación en una fila y nombres de columnas que sean
representativos. Para obtener un conjunto tidy, vamos a realizar
diversas transformaciones en nuestros datos para facilitar su análisis.

Comenzamos reorganizando las variables relacionadas con la intensidad
del tráfico (\texttt{INTA}, \texttt{INTAP}, \texttt{INTD},
\texttt{INTDP}, \texttt{INTT} y \texttt{INTTP}). Estas columnas
almacenan información sobre el sentido del tráfico (ascendente,
descendente o total) y el tipo de vehículo (pesado o total), por lo que
están estrechamente relacionadas entre sí.

Para convertir el conjunto de datos en tidy, optamos por transformar el
formato ancho en uno largo, de modo que cada fila represente una
combinación única de tramo, sentido y tipo de vehículo. Para ello
aplicamos la función pivot\_longer(), que nos permite condensar varias
columnas en dos nuevas variables: Sentido, que indica la dirección del
tráfico, y Tipo\_Vehiculo, que diferencia entre vehículos pesados (P) y
el total (T).

De forma análoga, se aplicaron transformaciones similares a otras
variables, como \texttt{TRAM}, las ubicaciones (\texttt{REFINI,\ REFFI})
y los puntos kilométricos (\texttt{PKINI,\ PKFI,\ PKE}). En el caso de
las variables de coordenadas (\texttt{PKECOOR,\ PKINICOOR,\ PKFICOOR}),
que distinguen entre la posición inicial, final y exacta, como cada
coordenada incluye la latitud y la longitud separadas por un punto y
coma, usamos la función \texttt{separate()} para dividir cada columna en
longitud y latitud. El separador decimal del conjunto eran las comas,
por lo que R detectaba las columnas como tipo carácter. Lo solucionamos
usando la función \texttt{sub()} para reemplazar las comas por puntos,
lo que nos permite convertir correctamente los valores a tipo numérico.
Después de convertirlas a tipo numérico, acabamos con las variables
\texttt{Latitud\_Inicio}, \texttt{Longitud\_Inicio},
\texttt{Latitud\_Final}, \texttt{Longitud\_Final},
\texttt{Latitud\_Exacta} y \texttt{Longitud\_Exacta}.

Solo falta asegurarnos de que los nombres de las columnas sean
representativos; para ello, utilizamos la función \texttt{rename()} y
reemplazamos algunos valores abreviados por descripciones completas
mediante la función \texttt{ifelse()}. Por ejemplo, en las variables
relacionadas con ubicación, los códigos \emph{INI}, \emph{E} y \emph{FI}
se sustituyeron por \emph{Inicial}, \emph{Exacta} y \emph{Final}; en
\texttt{Sentido}, los valores \emph{A} y \emph{D} pasaron a
\emph{Ascendente} y \emph{Descendente}; y en \texttt{Tipo\_Vehiculo},
\emph{T} y \emph{P} se cambiaron por \emph{Todos} y \emph{Pesados.}

\section{Análisis univariante y gráficos
exploratorios}\label{anuxe1lisis-univariante-y-gruxe1ficos-exploratorios}

En esta sección exploraremos los datos mediante un análisis univariante
de las variables númericas y el uso de gráficos. Las variables numéricas
de las que disponemos son \texttt{Flujo\_Vehiculos},
\texttt{Valor\_Punto\_Quilometrico}, y las coordenadas geográficas de
los puntos en los que se mide el flujo, así como las de los puntos que
se han designado como inicio y fin del tramo en el que se asume que el
tráfico es invariante. Estudiemos los diferentes estadísticos:

\begin{verbatim}
##                          Mínimo   Máximo    Rango      IQR   Q0.25  Mediana
## Latitud_Exacta            37.89    40.71     2.82     0.81   38.87    39.54
## Longitud_Exacta           -1.20     0.43     1.63     0.29   -0.64    -0.50
## Latitud_Inicio            37.89    40.65     2.76     0.81   38.86    39.53
## Longitud_Inicio           -1.21     0.43     1.65     0.28   -0.62    -0.49
## Latitud_Final             37.13    40.73     3.60     0.80   38.89    39.54
## Longitud_Final            -1.25     0.44     1.69     0.29   -0.64    -0.50
## Flujo_Vehiculos            0.00   999.00   999.00   175.84    4.16    16.63
## Valor_Punto_Quilometrico   0.00 95090.00 95090.00 22910.00 3500.00 10200.00
##                             Media    Q0.75 Desviación_típica
## Latitud_Exacta              39.32    39.68              0.65
## Longitud_Exacta             -0.47    -0.35              0.26
## Latitud_Inicio              39.32    39.66              0.64
## Longitud_Inicio             -0.47    -0.34              0.26
## Latitud_Final               39.32    39.69              0.65
## Longitud_Final              -0.47    -0.35              0.26
## Flujo_Vehiculos            142.66   180.00            232.95
## Valor_Punto_Quilometrico 18883.69 26410.00          21939.30
\end{verbatim}

Como era de esperar, las variables \texttt{Flujo\_Vehiculos} y
\texttt{Valor\_Punto\_Quilometrico} únicamente toman valores positivos,
lo cual es coherente con su naturaleza. Por otro lado, en las variables
que representan coordenadas geográficas (latitud y longitud, tanto
exactas como de inicio y fin del tramo), podemos ver que los
estadísticos muestran valores muy similares entre sí. No obstante, el
rango y el IQR de las coordenadas finales son mayores, especialmente en
la latitud, lo que nos indica que es probable que haya algún problema
con los datos de las coordenadas del tramo final, que veremos más
adelante.

Sin embargo, en la variable \texttt{Flujo\_Vehiculos} podemos ver que la
media (142.7) es mucho mayor que la mediana (16.6)(valor central), lo
que nos indica que la mayoría de los tramos registran flujos bajos, pero
que existen algunos tramos con valores muy altos (outliers) que quizás
dependen del tipo de vía que hacen que se eleve la media. Veamos si
estamos en lo cierto:

\pandocbounded{\includegraphics[keepaspectratio]{flujo_via.pdf}}

En los tres casos la distribución es claramente asimétrica hacia la
derecha, con la mayoría de los tramos registrando flujos bajos y unos
pocos con valores muy altos. Las vías convencionales concentran la mayor
cantidad de observaciones y presentan un pico en los flujos bajos,
mientras que las autovías y desdobladas muestran patrones similares,
aunque con algunos tramos de tráfico más intenso. Estos resultados
confirman la presencia de valores extremos que elevan la media de
\texttt{Flujo\_Vehiculos}. Por otro lado, cabe destacar que esta
variable no presenta una distribución gaussiana como podría haberse
esperado, sino una exponencial.

También podríamos preguntarnos si las variaciones del flujo se ven
afectadas por el \texttt{Sentido}, ya que los patrones de tráfico suelen
presentar asimetrías en los viajes de ida y vuelta. Veámoslo:

\pandocbounded{\includegraphics[keepaspectratio]{flujo_sentido.pdf}}

Se puede observar la gran similutd entre los histogramas del flujo en
sentido ascendente y descendente, lo que indica la ausencia de una
asimetría direccional en el tráfico de Valencia. Sin embargo, esta
homogeneidad en el sentido no implica estabilidad temporal, por lo que
resulta necesario analizar cómo varía el flujo a lo largo del tiempo
para identificar patrones mensuales que sí podrían revelar dinámicas
críticas para la gestión de la movilidad.

\pandocbounded{\includegraphics[keepaspectratio]{flujo_tiempo.pdf}}

Podemos ver que\texttt{Flujo\_Vehiculos} varía según el mes en el que
nos encontremos. Cabe destacar que se observa un máximo en abril, que
probablemente coincida con las fallas o Semana Santa que coincide con la
llegada de turistas a la ciudad. Por otro lado, en enero y junio
disminuye el tráfico, esto se puede deber a las vacaciones de navidad y
verano que la población suele viajar a nuevos destinos.

Una vez estudiado el flujo de vehículos, estudiemos que ocurre con la
variable numérica \texttt{Valor\_Punto\_Quilometrico}. Para ello
representemosla:

\pandocbounded{\includegraphics[keepaspectratio]{punto_quilometrico_hist.pdf}}

Se obserba que al igual que \texttt{Flujo\_Vehiculos},
\texttt{Valor\_Punto\_Quilometrico} parece seguir una distribución
exponencial, aunque no tan marcada. Lo que sugiere que los puntos
críticos de tráfico están altamente localizados, ya que se repiten con
frecuencia. Veamos si el \texttt{Tipo\_Vía} está relacionado con esta
idea:

\pandocbounded{\includegraphics[keepaspectratio]{punto_quilometrico.pdf}}

Cabe destacar que las autovías presentan los valores de punto
kilométrico más elevados y dispersos, indicando mayor frecuencia de
tráfico. Sin embargo, las vías desdobladas muestran una distribución más
concentrada con valores intermedios, mientras que las vías
convencionales registran los valores más bajos y compactos. También se
aprecia claramente como la gran cantidad de outliers presentes en
carreteras desdobladas y convencionales influyen en la discrepancia
entre la media y la mediana.

A continuación vamos a representar algunas variables categóricas, como
es el caso de \texttt{Tipo\_Via} y \texttt{Metodo\_Captacion}.

\pandocbounded{\includegraphics[keepaspectratio]{metodo.pdf}}

Fijémonos en que, si representamos el método de captación desglosándolo
según el tipo de carretera podemos sacar dos conclusiones: el método
dominante es espiras y las gomas solo se usan en carreteras
convencionales.

\pandocbounded{\includegraphics[keepaspectratio]{via.pdf}}

Por otro lado, en el gráfico \texttt{Tipo\_Via} se observa claramente
que hay más observaciones en las carreteras convencionales que en las
autovías o en las carreteras desdobladas.

En cuanto al resto de variables cualitativas,
\texttt{Codigo\_CV,\ Num\_Tramo,\ Sentido,\ Tipo\_Vehiculo,\ Ubicacion,\ Tipo\_Ubicacion\ y\ Tipo\_Valor\_Punto\_Quilometrico},
se ha decidido no representarlas por diversos motivos. El principal es
que, debido al alcance y los objetivos establecidos para este trabajo,
no resulta viable realizar una exploración exhaustiva de todas ellas.

Asimismo, existen razones vinculadas con la propia naturaleza de las
variables. En primer lugar,\texttt{Codigo\_CV\ y\ Num\_Tramo} presentan
un número excesivo de categorías, lo que dificulta su representación
gráfica de forma clara y significativa. En segundo lugar, la
representación de \texttt{Sentido},
\texttt{Tipo\_Vehiculo,\ Tipo\_Ubicacion} y
T\texttt{ipo\_Valor\_Punto\_Quilometrico} carecería de sentido, ya que
estas variables fueron generadas mediante la función pivot\_longer().
Por ello, las proporciones de sus valores son idénticas y, en
consecuencia, de carácter sintético, es decir, no aportan información
relevante para el análisis.

Por último, reparemos en las variables numéricas que todavía no hemos
explorado: las coordenadas geodésicas. Mediante el uso de las librerías
\texttt{sf} y \texttt{mapSpain} (que contiene mapas políticos de España
en particular) hemos representado los diferentes tipos de coordenadas en
las que se han tomado las mediciones. Empecemos por las exactas:

\pandocbounded{\includegraphics[keepaspectratio]{mapa_por_via.pdf}}

En este mapa puede comprobarse visualmente que las coordenadas son
correctas, ya que coinciden con el trazado de las carreteras de la
Comunidad Valenciana. Además, se observa, al igual que en el gráfico de
barras anterior, que el número de observaciones en carreteras
convencionales es considerablemente superior al de los demás tipos de
vía.

A continuación, representamos las coordenadas de los puntos iniciales y
finales de los tramos. Observando un único punto fuera del territorio a
estudiar, que probablemente se deba a un error en la recopilación de
datos.

\pandocbounded{\includegraphics[keepaspectratio]{mapa_incial.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{mapa_final.pdf}}

\section{Análisis bivariante}\label{anuxe1lisis-bivariante}

En este apartado, estudiaremos la linealidad, monotonía y dependencia de
las variables de nuestro conjunto de datos. En primer lugar,
comenzaremos con las variables numéricas, calculando las matrices de
correlación de Pearson y Spearman para determinar si existe una relación
lineal y una monotonía entre estas variables. Para ello, representamos
los coeficientes de Pearson y Spearman para cada par de variables.
Veámoslo:

\pandocbounded{\includegraphics[keepaspectratio]{cor.pdf}}

En la matriz de Pearson (izquierda) se observa una alta correlación
positiva entre las variables de latitud y longitud en sus diferentes
versiones. Lo que indica que dichas variables están estrechamente
relacionadas linealmente, lo cual tiene sentido por su naturaleza
geográfica. Por otro lado, la variable
\texttt{Valor\_Punto\_Quilometrico} presenta correlaciones positivas y
negativas (bajas) con las coordenadas geográficas. Esto es debido a que
esta variable es relativa a cada carretera o tramo. Sin embargo, la
variable \texttt{Flujo\_Vehiculos} no muestra una correlación lineal
significativa con el resto de las variables, lo que indica que el flujo
de vehículos no depende directamente de forma lineal con la posición
geográfica de los puntos de medición.

La matriz de Spearman (derecha) mantiene un patrón de correlaciones
similar al obtenido con Pearson, aunque con ligeras variaciones en la
magnitud de los coeficientes. Esto sugiere que las relaciones entre las
coordenadas mantienen su monotonía, aunque no de forma estrictamente
ascendente. Cabe destacar la correlación negativa entre
\texttt{Valor\_Punto\_Quilometrico} y las coordenadas se conserva,
confirmando la tendencia inversa entre ambas variables. De igual forma,
\texttt{Flujo\_Vehiculos} sigue mostrando baja relación con las demás
variables, confirmando su independencia respecto a la localización
geográfica.

Ahora estudiaremos la dependencia o independencia entre algunas
variables categóricas:
\texttt{Tipo\_Via}-\texttt{Metodologia\_Captacion},
\texttt{Tipo\_Via}-\texttt{Tipo\_Vehiculo} y
\texttt{Sentido}-\texttt{Tipo\_Vehiculo}. Para ello, calculamos el
coeficiente V de Cramer (que está acotado entre 0 y 1). Obteniendo,
respectivamente, 0.076, 0 y 0.

Indicándonos que hay una mínima dependencia entre las variables
\texttt{Tipo\_Via}-\texttt{Metodologia\_Captacion}. Sin embargo,
obtenemos un valor del coeficiente para los pares de variables
\texttt{Tipo\_Via}-\texttt{Tipo\_Vehiculo} y
\texttt{Sentido}-\texttt{Tipo\_Vehiculo} de 0; por tanto, ambos son
totalmente independientes. Podríamos pensar que existe alguna
dependencia entre el tipo de vehículo y el tipo de vía por la cual se
circula (autovía, convecional o desdoblada), pero observamos que no. En
cambio, ya esperábamos que el sentido de circulación (ascendente o
descendente) y el tipo de vehículo fueran completamente independientes
ya que los vehículos pueden circular indistintamente en un sentido o en
otro.

\section{Outliers}\label{outliers}

En este último apartado determinaremos los outliers (datos atípicos) de
algunas variables numéricas. Haremos el análisis con la variable
\texttt{Flujo\_Vehiculos} y, también, estudiaremos los outliers de esta
variable pero considerando solo los vehículos pesados. Así podremos
interpretar de una forma más completa los resultados.

Para detectar los outliers aplicaremos la regla de Hampel ya que utiliza
estimadores robustos y, además, no presupone que los datos siguen una
distribución gaussiana. Podremos observar los picos extremos de flujo de
vehículos tanto en el flujo total de vehículos como en el de vehículos
pesados.

Respecto a \texttt{Flujo\_Vehiculos} aparecen un total de 118878
outliers. Esta cantidad elevada (representa el 32.5\% del total de
registros) puede deberse a que tenemos un conjunto de datos muy segado
como podemos ver en las gráficas mostradas en la sección 4. Para
interpretar este resultado podemos ver si los outliers presentan alguna
relación con alguna otra variable, como por ejemplo, el día de la semana
(lunes, martes, etc.) o el tipo de vía.

Para ver si hay relación con el día de la semana podemos ver la
proporción de outliers (frecuencia relativa) con respecto al total de
outliers según el día:

\pandocbounded{\includegraphics[keepaspectratio]{freq_dias.eps}}

En este caso, vemos que de lunes a sábado hay una mayor proporción con
respecto a los domingos (aunque la distribución es prácticamente
uniforme). Esto puede deberse a que, de lunes a sábado, hay
desplazaminetos diaros de trabajadores o transportes de mercancías,
repartos, etc., que no se observan en domingo, y por ello, estos picos
más extremos de flujo de vehículos son más probables encontrarlos en
esos días.

Ahora, si observamos la proporción de outliers según el tipo de vía,
podemos detectar que hay una cantidad superior de outliers en
convencional que en autovía y desdoblada. Puede ser debido a que en
carretera convencional hay menos carriles, el límite de velocidad máxima
es inferior y, por tanto, tiene una menor capacidad de tráfico. Por
ello, cuando aparece algún pico de flujo de vehículos puede ser
considerado como outlier.

\pandocbounded{\includegraphics[keepaspectratio]{freq_vias.eps}}

Por otro lado, tenemos la variable \texttt{Tipo\_Vehiculo} que almacena
si el vehículo es pesado o no. Haciendo uso de la misma junto con
\texttt{Flujo\_Vehiculos}, podemos representar la frecuencia relativa de
outliers de vehículos pesados por día de la semana, al igual que hemos
hecho antes. Veámoslo:

\pandocbounded{\includegraphics[keepaspectratio]{freq_dias_pesados.pdf}}

Podemos ver que obtenemos un resultado parecido determinando la
proporción de outliers según el día de la semana. Aunque observamos que
en sábado y domingo la proporción es bastante menor con respecto al
resto de días, ya que en estos días los vehículos pesados no suelen
circular ya que no es día laboral.

De esta forma, podríamos mirar que ocurre con los resultados con
respecto al tipo de vía. Vemos que hay más outliers en carretera
desdoblada (aunque no hay una gran diferencia con los otros tipos de
vía). Como hemos visto antes, este tipo de vehículos transitan más por
este tipo de carretera (y por convencional). Entonces podemos entender
que los picos de flujo se encuentren en desdoblada (y convencional) por
una concentración de vehículos puntual.

\pandocbounded{\includegraphics[keepaspectratio]{freq_vias_pesados.pdf}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\vspace{6pt}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% optional

% Only for the journal Methods and Protocols:
% If you wish to submit a video article, please do so with any other supplementary material.
% \supplementary{The following supporting information can be downloaded at: \linksupplementary{s1}, Figure S1: title; Table S1: title; Video S1: title. A supporting video article is available at doi: link.}

% Only for journal Hardware:
% If you wish to submit a video article, please do so with any other supplementary material.
% \supplementary{The following supporting information can be downloaded at: \linksupplementary{s1}, Figure S1: title; Table S1: title; Video S1: title.\vspace{6pt}\\
%\begin{tabularx}{\textwidth}{lll}
%\toprule
%\textbf{Name} & \textbf{Type} & \textbf{Description} \\
%\midrule
%S1 & Python script (.py) & Script of python source code used in XX \\
%S2 & Text (.txt) & Script of modelling code used to make Figure X \\
%S3 & Text (.txt) & Raw data from experiment X \\
%S4 & Video (.mp4) & Video demonstrating the hardware in use \\
%... & ... & ... \\
%\bottomrule
%\end{tabularx}
%}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




\dataavailability{Los datos usados en este estudio son públicos
disponibles en
{[}\url{https://dadesobertes.gva.es/dataset/tra-int-veh-2025}{]}}

% Only for journal Nursing Reports
%\publicinvolvement{Please describe how the public (patients, consumers, carers) were involved in the research. Consider reporting against the GRIPP2 (Guidance for Reporting Involvement of Patients and the Public) checklist. If the public were not involved in any aspect of the research add: ``No public involvement in any aspect of this research''.}

% Only for journal Nursing Reports
%\guidelinesstandards{Please add a statement indicating which reporting guideline was used when drafting the report. For example, ``This manuscript was drafted against the XXX (the full name of reporting guidelines and citation) for XXX (type of research) research''. A complete list of reporting guidelines can be accessed via the equator network: \url{https://www.equator-network.org/}.}

% Only for journal Nursing Reports
%\guidelinesstandards{Please add a statement indicating which reporting guideline was used when drafting the report. For example, ``This manuscript was drafted against the XXX (the full name of reporting guidelines and citation) for XXX (type of research) research''. A complete list of reporting guidelines can be accessed via the equator network: \url{https://www.equator-network.org/}.}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Optional

%% Only for journal Encyclopedia
%\entrylink{The Link to this entry published on the encyclopedia platform.}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Optional
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{adjustwidth}{-\extralength}{0cm}

%\printendnotes[custom] % Un-comment to print a list of endnotes



% If authors have biography, please use the format below
%\section*{Short Biography of Authors}
%\bio
%{\raisebox{-0.35cm}{\includegraphics[width=3.5cm,height=5.3cm,clip,keepaspectratio]{Definitions/author1.pdf}}}
%{\textbf{Firstname Lastname} Biography of first author}
%
%\bio
%{\raisebox{-0.35cm}{\includegraphics[width=3.5cm,height=5.3cm,clip,keepaspectratio]{Definitions/author2.jpg}}}
%{\textbf{Firstname Lastname} Biography of second author}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% for journal Sci
%\reviewreports{\\
%Reviewer 1 comments and authors’ response\\
%Reviewer 2 comments and authors’ response\\
%Reviewer 3 comments and authors’ response
%}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\PublishersNote{}
\end{adjustwidth}


\end{document}
