---
title: "Mapas"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(dplyr)
library(tidyr)
library(ggplot2)
library(sf)
library(mapSpain)
library(readr)
library(VIM)
library(ggmosaic)
```

## Cargamos los datos:
```{r}
filename <-'data/intensidad_vehiculos_en_carretera_2025.csv'
vehiculos <- read.csv(filename, sep=";",encoding = "UTF-8")
guess_encoding(filename)
```

Renombramos para que los nombres sean más claros y pasamos `DIA` a formato `date`.
```{r}
new_names<-c(
  Intensidad_Ascendente="INTA",
  Intensidad_Ascendente_Pesada="INTAP",
  Intensidad_Descendente="INTD",
  Intensidad_Descendente_Pesada="INTDP",
  Intensidad_Total="INTT",
  Intensidad_Total_Pesados="INTTP",
  Metodo_Capatacion="TIPUSE",
  Tipo_Via="TIPUSV",
  Pto_Kilometrico_Final="PKFI",
  Pto_Kilometrico_Inicial="PKINI",
  Referencia_Inicio="REFINI",
  Referencia_Final="REFFI",
  Coord_Medicion="PKECOOR",
  Coord_Inicio="PKINICOOR",
  Coord_Fin="PKFICOOR",
  Pto_Kilometrico_Medicion="PKE",
  Fecha = "DIA"
  )
vehiculos2 <- vehiculos %>% 
  separate(TRAM, into = c("CV","Tramo"), sep = 2) %>% 
  mutate(DIA = as.Date(DIA,format="%d/%m/%Y")) %>% 
  mutate(Mes=format(DIA,"%B")) %>% 
  mutate(Mes = factor(
    Mes, 
    levels = c("January","February","March","April","May","June"),
    labels=c("Enero","Febrero","Marzo","Abril","Mayo","Junio"),
    ordered=TRUE
    )) %>% 
  rename(all_of(new_names))
head(vehiculos2)
```


## Variables cuantitativas
Fijémonos ahora en la distribución del flujo de vehículos no pesados :

```{r}
vehiculos2 %>%
  ggplot(aes(x = Intensidad_Total)) +
  geom_histogram(fill = "lavender",color="blue",binwidth=30) +
  labs(y="Recuento", x="Flujo total de vehículos no pesados") +
  facet_wrap(~ Tipo_Via, ncol = 3) +
  theme_minimal()

vehiculos2 %>%
  ggplot(aes(x = Intensidad_Total_Pesados)) +
  geom_histogram(fill = "lavender",color="blue",binwidth = 30) +
  labs(y="Recuento", x="Flujo total de vehículos pesados") +
  facet_wrap(~ Tipo_Via, ncol = 3) +
  theme_minimal()
```
# Plots con los datos en formato tidy

```{r}
vehiculos_tidy <- vehiculos %>% separate(col = TRAM, into = c('Codigo_CV', 'Num_Tramo'), sep = 2)

# INTA, INTAP, INTD, INTDP, INTT, INTTP: no son variables (hacemos lo mismo que con TRAM)
vehiculos_tidy <- vehiculos_tidy %>% pivot_longer(col = starts_with('INT'), names_to = c('Sentido', 'Tipo_Vehiculo'), names_pattern = '^INT([ADT]){1}(P?)$', values_to = 'Flujo_Vehiculos')

# En la columna Tipo_vehículo solo aparece si es pesado (P). Rellenamos el resto con T (= todos vehículos)
vehiculos_tidy <- vehiculos_tidy %>% mutate(Tipo_Vehiculo = ifelse(Tipo_Vehiculo == 'P', 'P', 'T'))

# Elimino las filas que en la variable Sentido tienen T(=ambos sentidos)
vehiculos_tidy <- vehiculos_tidy %>% filter(Sentido != 'T')

vehiculos_tidy <- vehiculos_tidy %>% pivot_longer(col = ends_with('COOR'), names_to = 'Coordenadas', names_pattern = '^PK(E|INI|FI)COOR$',  values_to = 'Valor_coordenada')%>% separate(col = Valor_coordenada, into = c('Latitud', 'Longitud'), sep=';') %>% pivot_longer(col = c(Latitud, Longitud), names_to = 'Tipo_Coordenada', values_to = 'Valor_Coordenada')%>% pivot_longer(col = starts_with('REF'), names_pattern = '^REF(INI|FI)',names_to = 'Tipo_Ubicacion', values_to = 'Ubicacion')%>% pivot_longer(col = matches('^PK(INI|FI|E)'), names_pattern = '^PK(INI|FI|E)',names_to = 'Tipo_Posicion_Punto_Quilometrico', values_to = 'Valor_Punto_Quilometrico')

str(vehiculos_tidy$Valor_Coordenada)
vehiculos_tidy$Valor_Coordenada <- sub(',', '.', vehiculos_tidy$Valor_Coordenada)
vehiculos_tidy$Valor_Coordenada <-as.numeric(vehiculos_tidy$Valor_Coordenada)
str(vehiculos_tidy$Valor_Coordenada)

#Renombramos algunas variables
vehiculos_tidy <- vehiculos_tidy %>% dplyr::rename(Fecha = DIA, Tipo_Via = TIPUSV, Metodologia_Captacion= TIPUSE)

vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico <-
  vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico %>%
  replace(. == "INI", "Inicial") %>%
  replace(. == "E", "Exacta") %>%
  replace(. == "FI", "Final")

vehiculos_tidy$Sentido <-
  vehiculos_tidy$Sentido %>%
  replace(. == "A", "Ascendente") %>%
  replace(. == "D", "Descendente")

vehiculos_tidy$Tipo_Vehiculo <-
  vehiculos_tidy$Tipo_Vehiculo %>%
  replace(. == "T", "Todos") %>%
  replace(. == "P", "Pesados")

vehiculos_tidy$Coordenadas <-
  vehiculos_tidy$Coordenadas %>%
  replace(. == "INI", "Inicial") %>%
  replace(. == "E", "Exacta") %>%
  replace(. == "FI", "Final")

vehiculos_tidy$Tipo_Ubicacion <-
  vehiculos_tidy$Tipo_Ubicacion %>%
  replace(. == "INI", "Inicial") %>%
  replace(. == "E", "Exacta") %>%
  replace(. == "FI", "Final")

vehiculos_tidy$Tipo_Via <-
  vehiculos_tidy$Tipo_Via %>%
  replace(. == "Aut.", "Autovia") %>%
  replace(. == "Conv.", "Convencional") %>%
  replace(. == "Desd.", "Desdoblada")
```

```{r}
mosaicplot(~ Metodologia_Captacion + Tipo_Via, data = vehiculos_tidy, color = c("#63b0b8","#d87373","#79a9c9"), las = 1)

mosaicplot(~ Metodo_Capatacion + Tipo_Via, data = vehiculos2, color = c("#63b0b8","#d87373","#79a9c9"), las = 1)

vehiculos2 %>% 
  ggplot(aes(Metodo_Capatacion)) + 
  geom_bar(color = "blue", fill = "lavender") +
  labs(x = "Método de captación", y = "Recuento") +
  theme_minimal()

vehiculos2 %>% 
  ggplot(aes(Tipo_Via)) + 
  geom_bar(color = "blue", fill = "lavender") +
  labs(x = "Tipo de vía", y = "Recuento") +
  theme_minimal()
```



```{r}
vehiculos_tidy %>% 
  ggplot() +
  geom_boxplot(aes(x=Tipo_Vehiculo, y=Flujo_Vehiculos)) +
  labs(x="Tipo de vehículos", y = "Flujo de vehículos")
  theme_minimal()

```




# mapita por si interesa

```{r}
valencia <- esp_get_munic_siane(region = "Comunidad Valenciana") %>%
     # Homogeinizo labels
    mutate(
        Provincia = esp_dict_translate(ine.prov.name, "es")
     )

vehiculos3 <- vehiculos2
coord_medicion <- vehiculos3 %>%
  mutate(Coord_Medicion = gsub(",",".",Coord_Medicion)) %>%
  separate(Coord_Medicion, into = c("Latitud","Longitud"), sep=";") %>%
  mutate(Latitud = as.numeric(Latitud)) %>%
  mutate(Longitud = as.numeric(Longitud)) %>% 
  select("Latitud", "Longitud","Tipo_Via") %>%
  distinct

coord_medicion_sf <- st_as_sf(coord_medicion, coords = c("Longitud", "Latitud"), crs = 4326)

# ggplot() +
#   geom_sf(data = valencia, fill = "lavender") +
#   geom_sf(data = coord_medicion_sf, col = Tipo_Via, size = 1) +
#   theme_minimal()

coord_inicio <- vehiculos3 %>%
  mutate(Coord_Inicio = gsub(",",".",Coord_Inicio)) %>%
  separate(Coord_Inicio, into = c("Latitud","Longitud"), sep=";") %>%
  mutate(Latitud = as.numeric(Latitud)) %>%
  mutate(Longitud = as.numeric(Longitud)) %>% 
  select("Latitud", "Longitud") %>%
  distinct

coord_inicio_sf <- st_as_sf(coord_inicio, coords = c("Longitud", "Latitud"), crs = 4326)

ggplot() +
  geom_sf(data = valencia, fill = "beige") +
  geom_sf(data = coord_inicio_sf, color = "blue", size = 1) +
  theme_minimal()

coord_fin <- vehiculos3 %>%
  mutate(Coord_Fin = gsub(",",".",Coord_Fin)) %>%
  separate(Coord_Fin, into = c("Latitud","Longitud"), sep=";") %>%
  mutate(Latitud = as.numeric(Latitud)) %>%
  mutate(Longitud = as.numeric(Longitud)) %>% 
  select("Latitud", "Longitud") %>%
  distinct

coord_fin_sf <- st_as_sf(coord_fin, coords = c("Longitud", "Latitud"), crs = 4326)

ggplot() +
  geom_sf(data = valencia, fill = "beige") +
  geom_sf(data = coord_fin_sf, color = "blue", size = 1) +
  theme_minimal()
```

```{r}
vehiculos3 <- vehiculos2
coord_medicion <- vehiculos3 %>%
  mutate(Coord_Medicion = gsub(",",".",Coord_Medicion)) %>%
  separate(Coord_Medicion, into = c("Latitud","Longitud"), sep=";") %>%
  mutate(Latitud = as.numeric(Latitud)) %>%
  mutate(Longitud = as.numeric(Longitud)) %>% 
  mutate(Tipo_Via = factor(Tipo_Via, levels=c("Aut.", "Conv.", "Desd."), labels= c("Autovía", "Convencional", "Desdoblada"))) %>% 
  select("Latitud", "Longitud","Tipo_Via") %>%
  distinct

coord_medicion_sf <- st_as_sf(coord_medicion, coords = c("Longitud", "Latitud"), crs = 4326)

par(mfrow = c(1, 2))

ggplot() +
  geom_sf(data = valencia, fill = "beige") +
  geom_sf(data = coord_medicion_sf, aes(col = Tipo_Via), size = 1) +
  scale_color_manual("Tipos de vía",values=c("#d87373","#63b0b8","blue")) +
  theme_minimal()

# esta es la buena
ggplot() +
  geom_sf(data = valencia, fill = "beige") +
  geom_sf(data = coord_medicion_sf,aes(col = Tipo_Via), size = 1) +
  scale_color_manual(guide="none",values=c("#d87373","#63b0b8","blue")) +
  facet_wrap(~ Tipo_Via, ncol = 3) +
  theme_minimal()
```

