---
title: "ProyectoAED"
author: "María de los Ángeles Díaz Castro, Ana Blasco Vega e Irene Barba La Orden "
date: "2025-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cargamos los datos:
```{r}
library(readr)
filename <-'data/intensidad_vehiculos_en_carretera_2025.csv'
vehiculos <- read.csv(filename, sep=";",encoding = "UTF-8")
guess_encoding(filename)
```

```{r}
rm(vehiculos_tidy)
library(tidyr)
library(dplyr)
library(VIM)
glimpse(vehiculos)
```
```{r}
aggr(vehiculos, prop = FALSE, combined = TRUE, numbers = TRUE, sortVars = TRUE, sortCombs = TRUE, plot = TRUE)
```


## Dataframe TIDY
```{r}

# Comprobamos de qué tipo es cada variable
sapply(vehiculos, class)
# Hay que transformar la variable DIA de caracter a fecha
vehiculos$DIA <- as.Date(vehiculos$DIA, format = '%d/%m/%Y')
class(vehiculos$DIA)

# Tiene que ser un dataset tidy (para trabajar más fácilmente), entonces comprobamos cuáles son las variables y reorganizamos si es necesario

# TRAM: Separamos la 'variable' TRAM en dos variables (XX código CV de la carretera + XXX número de tramo)
# Comprobamos que todos los valores tienen 5 dígitos
all(length(vehiculos$TRAM == 5))
vehiculos_tidy <- vehiculos %>% separate(col = TRAM, into = c('Codigo_CV', 'Num_Tramo'), sep = 2)

# INTA, INTAP, INTD, INTDP, INTT, INTTP: no son variables (hacemos lo mismo que con TRAM)
vehiculos_tidy <- vehiculos_tidy %>% pivot_longer(col = starts_with('INT'), names_to = c('Sentido', 'Tipo_Vehiculo'), names_pattern = '^INT([ADT]){1}(P?)$', values_to = 'Intensidad')

# En la columna Tipo_vehículo solo aparece si es pesado (P). Rellenamos el resto con T (= todos vehículos)
vehiculos_tidy <- vehiculos_tidy %>% mutate(Tipo_Vehiculo = ifelse(Tipo_Vehiculo == 'P', 'P', 'T'))

# Elimino las filas que en la variable Sentido tienen T(=ambos sentidos)
vehiculos_tidy <- vehiculos_tidy %>% filter(Sentido != 'T')
head(vehiculos)

```

```{r}
# PK(E|INI|FI)COOR separamos estas variables según la coordenada (inicial, final, exacta); según si se mide latitud/longitud y el valor

# PK(INI|FI|E) separamos según el tipo (inicial, final, exacto) y el valor

# REF(INIFI) separamos según el tipo de ubicación (inicial, final) y valor

vehiculos_tidy <- vehiculos_tidy %>% pivot_longer(col = ends_with('COOR'), names_to = 'Coordenadas', names_pattern = '^PK(E|INI|FI)COOR$',  values_to = 'Valor_coordenada')%>% separate(col = Valor_coordenada, into = c('Latitud', 'Longitud'), sep=';') %>% pivot_longer(col = c(Latitud, Longitud), names_to = 'Tipo_Coordenada', values_to = 'Valor_Coordenada')%>% pivot_longer(col = starts_with('REF'), names_pattern = '^REF(INI|FI)',names_to = 'Tipo_Ubicacion', values_to = 'Ubicacion')%>% pivot_longer(col = matches('^PK(INI|FI|E)'), names_pattern = '^PK(INI|FI|E)',names_to = 'Tipo_Posicion_Punto_Quilometrico', values_to = 'Valor_Punto_Quilometrico')

str(vehiculos_tidy$Valor_Coordenada)
vehiculos_tidy$Valor_Coordenada <- sub(',', '.', vehiculos_tidy$Valor_Coordenada)
vehiculos_tidy$Valor_Coordenada <-as.numeric(vehiculos_tidy$Valor_Coordenada)
str(vehiculos_tidy$Valor_Coordenada)

#Renombramos algunas variables
vehiculos_tidy <- vehiculos_tidy %>% dplyr::rename(Fecha = DIA, Tipo_Via = TIPUSV, Metodologia_Captacion= TIPUSE)

# Rescribimos algunos valores
#vehiculos_tidy$Coordenadas <- ifelse(vehiculos_tidy$Coordenadas == 'INI', 'Iniciales', ifelse(vehiculos_tidy$Coordenadas == 'E', 'Exactas', ifelse(vehiculos_tidy$Coordenadas == 'FI', 'Finales', vehiculos_tidy$Coordenadas)))

#vehiculos_tidy$Tipo_Ubicacion <- ifelse(vehiculos_tidy$Tipo_Ubicacion == 'INI', 'Inicial', ifelse(vehiculos_tidy$Tipo_Ubicacion == 'E', 'Exacta', ifelse(vehiculos_tidy$Tipo_Ubicacion == 'FI', 'Final', vehiculos_tidy$Tipo_Ubicacion)))

#vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico <- ifelse(vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico == 'INI', 'Inicial', ifelse(vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico == 'E', 'Exacta', ifelse(vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico == 'FI', 'Final', vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico)))

#vehiculos_tidy$Sentido <- ifelse(vehiculos_tidy$Sentido == 'A', 'Ascendente', ifelse(vehiculos_tidy$Sentido == 'D', 'Descendente', vehiculos_tidy$Sentido))

#vehiculos_tidy$Tipo_Vehiculo <- ifelse(vehiculos_tidy$Tipo_Vehiculo == 'T', 'Todos', ifelse(vehiculos_tidy$Tipo_Vehiculo == 'P', 'Pesados', vehiculos_tidy$Tipo_Vehiculo))

#optimizado: 
library(dplyr)

vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico <-
  vehiculos_tidy$Tipo_Posicion_Punto_Quilometrico %>%
  replace(. == "INI", "Inicial") %>%
  replace(. == "E", "Exacta") %>%
  replace(. == "FI", "Final")

vehiculos_tidy$Sentido <-
  vehiculos_tidy$Sentido %>%
  replace(. == "A", "Ascendente") %>%
  replace(. == "D", "Descendente")

vehiculos_tidy$Tipo_Vehiculo <-
  vehiculos_tidy$Tipo_Vehiculo %>%
  replace(. == "T", "Todos") %>%
  replace(. == "P", "Pesados")

vehiculos_tidy$Coordenadas <-
  vehiculos_tidy$Coordenadas %>%
  replace(. == "INI", "Inicial") %>%
  replace(. == "E", "Exacta") %>%
  replace(. == "FI", "Final")

vehiculos_tidy$Tipo_Ubicacion <-
  vehiculos_tidy$Tipo_Ubicacion %>%
  replace(. == "INI", "Inicial") %>%
  replace(. == "E", "Exacta") %>%
  replace(. == "FI", "Final")

vehiculos_tidy$Tipo_Via <-
  vehiculos_tidy$Tipo_Via %>%
  replace(. == "Aut.", "Autovia") %>%
  replace(. == "Conv.", "Convencional") %>%
  replace(. == "Desd.", "Desdoblada")




head(vehiculos_tidy)

```

